### ISSUE TITLE
Add Thumbnail to Post Menu

### ISSUE THREAD

**Issue by soroosj** [nathancday/min_night#10]
Hi Nathan

In the posts menu (link [here)](https://soroosj.netlify.com/post/), I am hoping to add a thumbnail image next to the title of each post entry.

From Googling I tried adding "thumbnail" and "featured_image" below "title" in the Rmd file header of my content/posts folder.  Didn't seem to work.  

I am familiar with R but very new to blogdown and hugo so hopefully not a dumb question.

My site is at https://github.com/soroosj/r_site if it helps. Thanks for any ideas you may have.

**Comment by nathancday** [comment]
Right now there is no support for adding a thumbnail like that. The only image support is for Twitter cards.

You could add that behavior by editting this template file: layouts/partials/list-item-post.html With the relevant HTML to hold an image and then similar Go snippets to pull the file path from the markdown header and insert it on a page by page basis.

**Comment by soroosj** [comment]
Thanks for the idea, Nate.
