### ISSUE TITLE
Bad licence used on generated site

### ISSUE THREAD

**Issue by kb2623** [nathancday/min_night#11]
Hi,
you have a **MIT license** on you repository, but on the generated site you have different license, a **CC license**. Please fix this license issue or use the right license and update the license on Hugo themes site.

I was looking at the reference theme called [minimal](https://github.com/calintat/minimal) and I saw a **MIT license** on that repository. You must include copyright and license from the base theme!

**Comment by nathancday** [comment]
You are correct this theme is MIT licensed, just like the original Minimal. However the example site (and my personal blog) are [CC-by](https://creativecommons.org/licenses/by/4.0/) so the work/posts there are properly credited if someone wants to reshare the content. Hope you have a nice day!
