### ISSUE TITLE
Night toggle not working for blogdown-rendered rmarkdown posts

### ISSUE THREAD

**Issue by conradborchers** [nathancday/min_night#14]
Dear Nate,

I am very new to building websites and set up a workflow with Hugo, your theme min_night and Rmarkdown (employing the r-package blogdown). I render my site using the function blogdown::build_site() and it correctly includes all the HTML output-pages as blog posts. However, the night mode toggle does not work on those pages that were particularly rendered from Rmarkdown files. You can go back to other pages and select your mode but once you go on a Rmarkdown post it is unchangeable. Maybe you could share how you publish Rmarkdown documents on your personal website where this issue seems not to exist?

Many thanks and kind regards
Conrad

**Comment by nathancday** [comment]
Hard to say what is causing your problem, but I use `.Rmd` files for my site, here is an example
https://github.com/nathancday/new_site/blob/master/content/post/2019-12-15-owning-outlines-in-rstudio.Rmd

I've never used the `.Rmarkdown` file format so perhaps switching off that to `.Rmd` will solve.

Feel free to link to your blog repo and a problematic post.

**Comment by conradborchers** [comment]
Thanks! Changing the file extension to `.Rmd` nor implementing your sample code seems to fix the problem. The repository is here:
https://github.com/conradborchers/hugo/
the website with the sample post is here:
https://conradborchers.netlify.app/. 

Additionally, I am compiling the website from the command line with the following R-script:
`setwd("C:/mypath")`
`blogdown::build_site()`

**Comment by nathancday** [comment]
I see you have modified the min_night theme's [partials/single.html](https://github.com/conradborchers/hugo/commits/master/themes/min_night/layouts/_default/single.html) template. If you revert your repo to the [commit sha c024bcc4915787d8edaee23c390ffdfacfdc00f9](https://github.com/conradborchers/hugo/commit/c024bcc4915787d8edaee23c390ffdfacfdc00f9#diff-3164a9ca5e68033c9d66cb44bdda2ef3) Rmd files render properly with night mode. So something got corrupted by your edits.

Try this out with `git checkout c024bcc4915787d8edaee23c390ffdfacfdc00f9#diff-3164a9ca5e68033c9d66cb44bdda2ef3` and then `blogdown::serve_site()`.

**Comment by conradborchers** [comment]
Thank you, it seems like I indeed changed the file inappropriately...
However, I reverted my repository to the commit you mentioned under the
commit 8f55562 now, then I just added a sample R-Markdown post under
commit 0d5beab and the issue still exists. Should I maybe consider
resetting to the first version of your template entirely?

**Comment by nathancday** [comment]
I would. Then add one thing at a time and see when it breaks.
