### ISSUE TITLE
How to make the author visible

### ISSUE THREAD

**Issue by xfim** [nathancday/min_night#4]
Hello,

Thank you for your effort in creating min_night.

I am using the theme and I would like to know if it is possible to make the author of the post appear in the post (maybe just after the title), or the author in the config.toml somewhere in the colored area. I have achieved the second one by manually adding it as an entry in the menu, but I was wondering if the theme has been designed with something like this in mind.

Thank you.

**Comment by nathancday** [comment]
after the quickstart code on the README, in `bash` run:

```
mkdir layouts/partials/
cp themes/min_night/layouts/partials/list-item.html layout/partials/
```

to copy the layout template for `list-item.html` into your sites top level directory. Any file templates in `layout/` will overwrite the defaults from `themes/min_night/layout`.

Now edit the HTML building section in `layouts/partials/list-item.html`:

```
<h4><a href="{{ .Scratch.Get "link" }}">{{ .Title }}</a></h4>
<h5>Author: {{ .Site.Params.author}}</h5> <!-- newline!!! -->
<h5>{{ $.Scratch.Get "pub_date" }} - {{ $.Scratch.Get "read_time" }} minutes</h5>
<h5>{{ $.Scratch.Get "subtitle" }}</h5>
```

to add the `author` parameter from the config.toml file, to the list item for display.

**Comment by nathancday** [comment]
I'm gonna close this because I haven't heard anything back, if you need more help just re-open it

**Comment by xfim** [comment]
Excellent. Thank you very much.
