### ISSUE TITLE
How much work would be needed to implement this as solarized?

### ISSUE THREAD

**Issue by cognitiaclaeves** [nathancday/min_night#7]
I'm new to hugo and in the process of converting my blog from Jekyll to Hugo. I'd like to use solarized light/dark for my day/night modes. How much work would it be to change the colors for this theme?

**Comment by nathancday** [comment]
Quite a bit, I'm afraid. Right now the theme works via a 180* hue rotation, so it would need to be adjusted to allow a specific palette for each mode.

Existing caveats: The "light" theme is the only one directly encoded (night mode is the rotated version), and even then I'm only exposing the dark accent color for specification in config.toml (the background is always light grey). You could make something very similar to Solarized, if you edit `static/main.css` directly.

I really do like this idea and Solarized in general. I'm going to look at it a bit more.
